[package]
authors = ["KILT <info@kilt.io>"]
edition = "2018"
name = "kilt-primitives"
version = "0.1.0"

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.101", optional = true, features = ["derive"]}

sp-core = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "master"}
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "master"}
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "master"}
sp-consensus-aura = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "master"}

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-consensus-aura/std",
  "sp-runtime/std",
  "sp-core/std",
  "serde",
]
