[package]
authors       = { workspace = true }
description   = "Runtime APIs for integrating the unique-lookup capabilities."
documentation = { workspace = true }
edition       = { workspace = true }
homepage      = { workspace = true }
license-file  = { workspace = true }
name          = "unique-linking-runtime-api"
readme        = { workspace = true }
repository    = { workspace = true }
version       = { workspace = true }

[dependencies]
# External dependencies
parity-scale-codec = { workspace = true }

# Substrate dependencies
sp-api = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std     = ["parity-scale-codec/std", "sp-api/std", "sp-std/std"]
