[package]
authors       = { workspace = true }
description   = "Runtime APIs for dealing with the bonded currency pallet."
documentation = { workspace = true }
edition       = { workspace = true }
homepage      = { workspace = true }
license-file  = { workspace = true }
name          = "pallet-bonded-currency-runtime-api"
readme        = { workspace = true }
repository    = { workspace = true }
version       = { workspace = true }

[dependencies]
# External dependencies
parity-scale-codec = { workspace = true }
scale-info         = { workspace = true }

# Internal dependencies
pallet-bonded-coins = { workspace = true }

# Substrate dependencies
sp-api = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
  "pallet-bonded-coins/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "sp-api/std",
  "sp-std/std",
]
