name: Try-runtime

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - 'refs/tags/[0-9]+.[0-9]+.[0-9]+*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  TRY_RUNTIME_CLI_VERSION_TAG: v0.7.0
  CARGO_HOME: ./.cargo

jobs:
  test-try-runtime:
    strategy:
      matrix:
        runtime: [peregrine, spiritnet]
    runs-on: ubuntu-latest
    outputs:
      head-commit-msg: ${{ steps.step-head-commit.outputs.headCommitMsg }}
    container:
      image: paritytech/ci-unified:bullseye-1.74.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get Head Commit Message
        id: step-head-commit
        run: echo "headCommitMsg=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"

      - name: Set up caching for Cargo
        if: ${{ !contains(steps.step-head-commit.outputs.headCommitMsg, 'ci-skip-rust') }}
        uses: actions/cache@v4
        with:
          path: ${{ secrets.CARGO_CACHE_PATH }}
          key: cargo-try-runtime-${{ matrix.runtime }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-try-runtime-${{ matrix.runtime }}-${{ github.ref_name }}-

      - name: Run try-runtime
        if: ${{ !contains(steps.step-head-commit.outputs.headCommitMsg, 'ci-skip-rust') }}
        run: |
          echo "Running ${{ matrix.runtime }} runtime migration check"

          echo "---------- Downloading try-runtime CLI ----------"
          curl -sL https://github.com/paritytech/try-runtime-cli/releases/download/${{ env.TRY_RUNTIME_CLI_VERSION_TAG }}/try-runtime-x86_64-unknown-linux-musl -o try-runtime
          chmod +x ./try-runtime
          echo "Using try-runtime-cli version:"
          ./try-runtime --version

          echo "---------- Building ${{ matrix.runtime }} runtime ----------"
          cargo build --release --locked -p ${{ matrix.runtime }}-runtime --features try-runtime

          echo "---------- Executing on-runtime-upgrade for ${{ matrix.runtime }} ----------"
          ./try-runtime --runtime ./target/release/wbuild/${{ matrix.runtime }}-runtime/${{ matrix.runtime }}_runtime.compact.compressed.wasm \
              on-runtime-upgrade --disable-spec-version-check --checks=all live --uri wss://${{ matrix.runtime }}.kilt.io
