name: Try-runtime

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TRY_RUNTIME_CLI_VERSION_TAG: v0.7.0
  CARGO_HOME: ./.cargo

jobs:
  get-head-commit-msg:
    runs-on: ubuntu-latest
    outputs:
      head-commit-msg: ${{ steps.step-head-commit.outputs.headCommitMsg }}
    steps:
      - uses: actions/checkout@v4head-commit-msg
      - name: Get Head Commit Message
        id: step-head-commit
        run: echo "headCommitMsg=$(git log -1 --pretty=format:%s)" >> "$GITHUB_OUTPUT"


  test-try-runtime:
    strategy:
      matrix:
        runtime: [peregrine, spiritnet]
    runs-on: ubuntu-latest
    needs: get-head-commit-msg
    if: ${{ !contains(needs.get-head-commit-msg.outputs.head-commit-msg, 'ci-skip-rust') }}
    container:
      image: paritytech/ci-unified:bullseye-1.74.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up caching for Cargo
        uses: actions/cache@v4
        with:
          path: ${{ secrets.CARGO_CACHE_PATH }}
          key: cargo-try-runtime-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-try-runtime-${{ matrix.runtime }}-

      - name: Run try-runtime
        run: |
          echo "Running ${{ matrix.runtime }} runtime migration check"

          echo "---------- Downloading try-runtime CLI ----------"
          curl -sL https://github.com/paritytech/try-runtime-cli/releases/download/${{ env.TRY_RUNTIME_CLI_VERSION_TAG }}/try-runtime-x86_64-unknown-linux-musl -o try-runtime
          chmod +x ./try-runtime
          echo "Using try-runtime-cli version:"
          ./try-runtime --version

          echo "---------- Building ${{ matrix.runtime }} runtime ----------"
          cargo build --release --locked -p ${{ matrix.runtime }}-runtime --features try-runtime

          echo "---------- Executing on-runtime-upgrade for ${{ matrix.runtime }} ----------"
          ./try-runtime --runtime ./target/release/wbuild/${{ matrix.runtime }}-runtime/${{ matrix.runtime }}_runtime.compact.compressed.wasm \
              on-runtime-upgrade --disable-spec-version-check --checks=all live --uri wss://${{ matrix.runtime }}.kilt.io
